#
# create empty scene
#
/nDet/detector/setGeometry ellipse
/nDet/detector/setDetectorLength 20
/nDet/detector/update
/nDet/analysis/outputFile Neutrons_3000keV_ellipse_TeflonMylar_20cm.root
#/nDet/analysis/outputFile cona.root
#/hits/inactivate /theScintSD
#/tracking/verbose 1
# Now ready for /run/beamOn
/gps/particle neutron
#/gps/particle gamma
/gps/energy  3000 keV
/gps/direction 0 -1 0
#/gps/pos/type Plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1
#/gps/pos/shape Rectangle
/gps/pos/centre 0 10 0 cm
#/gps/pos/halfx 1.5 cm
#/gps/pos/halfy 9. cm
/gps/ang/type planar
/run/beamOn 100000

#/run/beamOn 1
 
