#
# create empty scene
#
/nDet/detector/setGeometry array
/nDet/detector/setDetectorLength 20.
/nDet/detector/setDetectorWidth 10.
/nDet/detector/setMylarThickness 0.
/nDet/detector/update
/nDet/analysis/outputFile NEXT_Array_20cm_1MeV_n_uniform.root
#/nDet/analysis/outputFile cona.root
#/hits/inactivate /theScintSD
#/tracking/verbose 1
/gps/particle neutron
#/gps/particle gamma
#/gps/ang/type iso
#/gps/position 20 0 0 cm
#/gps/position 0 20 0 cm
#Uncomment for an extended distribution
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 20 0 cm
/gps/pos/halfx 2.5 cm
/gps/pos/halfy 10 cm
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1

/gps/ang/type planar

#/gps/direction -1 0 0 
/gps/direction 0 -1 0 
/gps/energy  1 MeV
# Now ready for /run/beamOn
/run/beamOn 200000

#/run/beamOn 10
 
