#
# create empty scene
#
#/vis/scene/create

#/tracking/verbose 2

#OGLIX
/vis/open OGL
#HepRepFile
#/vis/open HepRepFile

/vis/drawVolume

/vis/scene/add/trajectories

#/vis/scene/add/hits

/vis/viewer/set/viewpointThetaPhi 90 0
#/vis/viewer/panTo 0.085 0.005 

/vis/viewer/set/viewpointVector -1 1 1
#/vis/viewer/set/background 0.7 0.9 0.5

#/vis/viewer/zoom 4

#
# Refresh ready for run
/vis/viewer/refresh
#
# Now ready for /run/beamOn
#/run/beamOn 100000
