#
# create empty scene
#
/nDet/detector/setGeometry arrayhex
/nDet/detector/setSiPMdimensions 6
/nDet/detector/update
/nDet/analysis/outputFile NEXT_sim_1MeV_neutrons_arrayhex.root
#/nDet/analysis/outputFile cona.root
#/hits/inactivate /theScintSD
#/tracking/verbose 1
# Now ready for /run/beamOn
/gps/particle neutron
#/gps/particle e-
/gps/energy  1000 keV
/gps/direction 1 0 0
/gps/pos/type Plane
#/gps/pos/rot1  0 0 1
#/gps/pos/rot2 0 1 0
/gps/pos/shape Rectangle
/gps/pos/centre -25 1 0 cm
#/gps/pos/centre 0 0 0 cm
/gps/pos/halfx 10. cm
/gps/pos/halfy 4.5 cm
/gps/ang/type planar
/run/beamOn 100
#/vis/scene/endOfEventAction accumulate
#/run/beamOn 5 
 
