# Get the commit number
COMMIT_NUMBER=`git show --pretty=format:"%h" --no-patch`

# Get the commit date
COMMIT_DATE=`git show --pretty=format:"%ci" --no-patch | cut -d ' ' -f1`

# Get the current branch
COMMIT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`

echo "/** @file version.hh"
echo "  * @brief Header containing the current NEXTsim commit number which is being used"
echo "  * This file is automatically generated by CMake whenever a change to the current"
echo "  * repository branch is detected and should not be modified by the user" 
echo "  */"
echo ""
echo "#ifndef NDET_VERSION_HH"
echo "#define NDET_VERSION_HH"
echo ""
echo "#define VERSION_STRING \"${COMMIT_NUMBER}-${COMMIT_BRANCH} (${COMMIT_DATE})\""
echo ""
echo "#endif"
